export const actionTypes = {
  GET_DATA_FROM_DB: "GET_DATA_FROM_DB",
  ADD_DIARY: "ADD_DIARY",
  TOGGLE_NAVIGATION_BAR: "TOGGLE_NAVIGATION_BAR",
  IS_LOGGED: "IS_LOGGED",
  ADD_IMAGE: "ADD_IMAGE",
  ADD_IMAGES_FROM_BACK: "ADD_IMAGES_FROM_BACK",
  DELETE_WEEK: "DELETE_WEEK",
  ADD_WEEK: "ADD_WEEK",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};
